id: DDF3372F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T11:08:32+00:00'
last_modified: '2022-05-30T07:54:36.845265+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '2596':
      image_group_id: I1PD95959
      title: རྟེན་ཅིང་འབྲེལ་པར་འབྱུང་བའི་དེ་ཁོ་ན་ཉིད།
      total_pages: 1872
      order: 114
      base_file: 2596.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
