id: PC4BE3C50
initial_creation_type: ocr
source_metadata:
  volumes:
    d920d943743e4fe693af483b70ee972c:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: རྟེན་ཅིང་འབྲེལ་པར་འབྱུང་བའི་དེ་ཁོ་ན་ཉིད།
      total_pages: 1872
      volume_number: 114
